title: HICS.hu
description: > # this means to ignore newlines until "baseurl:"
  Humán Innovációs Csoport Nonprofit Kft.
baseurl: "/rebase_hics" # the subpath of your site, e.g. /blog
url: "https://ardrift.github.io" # the base hostname & protocol for your site

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Hum%C3%A1n-Innov%C3%A1ci%C3%B3s-Csoport-Nonprofit-Kft-671616819581186/
  - title: linkedin
    url: https://www.linkedin.com/company/human-innov%C3%A1ci%C3%B3s-csoport-nonprofit-kft-/

# Build settings
markdown: kramdown
permalink: pretty
