backend:
  name: github
  repo: ArDrift/rebase_hics
  branch: master # Branch to update (optional; defaults to master)
  site_domain: rebase-hics.netlify.com
  accept_roles:
    - admin
    - editor

media_folder: "/assets/img/projects" # Media files will be stored in the repo under images/uploads

collections:
  - name: "projekt" # Used in routes, e.g., /admin/collections/blog
    label: "Projekt [HU]" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: lang
      value: hu
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Cím", name: "title", widget: "text"}
      - {label: "Nyelv", name: "lang", widget: "select", options: ["en", "hu"], default: "hu"}
      - {label: "Link", name: "ref", widget: "string"}
      - {label: "Kép", name: "img", widget: "image"}
      - {label: "Leírás", name: "description", widget: "text"}
      - {label: "Szöveg", name: "body", widget: "markdown"}
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project [EN]" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    filter:
      field: lang
      value: en
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Cím", name: "title", widget: "text"}
      - {label: "Nyelv", name: "lang", widget: "select", options: ["en", "hu"], default: "hu"}
      - {label: "Link", name: "ref", widget: "string"}
      - {label: "Kép", name: "img", widget: "image"}
      - {label: "Leírás", name: "description", widget: "text"}
      - {label: "Szöveg", name: "body", widget: "markdown"}
  - name: "szekcio" # Used in routes, e.g., /admin/collections/blog
    label: "Szekció [HU]" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    filter:
      field: lang
      value: hu
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Cím", name: "title", widget: "string"}
      - {label: "Menüpont neve", name: "nav", widget: "string"}
      - {label: "Szöveg", name: "body", widget: "markdown"}
  - name: "section" # Used in routes, e.g., /admin/collections/blog
    label: "Section [EN]" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    filter:
      field: lang
      value: en
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Cím", name: "title", widget: "string"}
      - {label: "Menüpont neve", name: "nav", widget: "string"}
      - {label: "Szöveg", name: "body", widget: "markdown"}
