backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/assets/img/projects" # Media files will be stored in the repo under images/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projektek" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Cím", name: "title", widget: "text"}
      - {label: "Nyelv", name: "lang", widget: "select", options: ["en", "hu"] default: "hu"}
      - {label: "Link", name: "ref", widget: "string"}
      - {label: "Kép", name: "img", widget: "image"}
      - {label: "Leírás", name: "description", widget: "text"}
      - {label: "Szöveg", name: "body", widget: "markdown"}
